/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ScreenPackage;

import java.awt.Color;
import javax.swing.ImageIcon;
import javax.swing.JFrame;


/**
 *
 * @author Admin
 */
public class HowToPlay extends javax.swing.JFrame {

    /**
     * Creates new form HowToPlay
     */
    public HowToPlay() {
        initComponents();
        this.setTitle("Dinosaur");
        ImageIcon img = new ImageIcon("src/data/main-character1.png");
        this.setIconImage(img.getImage());
        lblBackGround.setBackground(Color.decode("#f7f7f7"));
        this.setLocationRelativeTo(null);
        this.setResizable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        lblBackGround = new javax.swing.JPanel();
        lblTitle = new javax.swing.JLabel();
        logo = new javax.swing.JLabel();
        lblUpAndDown = new javax.swing.JLabel();
        lblPlay = new javax.swing.JLabel();
        lblTextDown = new javax.swing.JLabel();
        lblTextPlay1 = new javax.swing.JLabel();
        lblTextUp = new javax.swing.JLabel();
        btnBack = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jTextArea1.setText("To ");
        jScrollPane1.setViewportView(jTextArea1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblBackGround.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        lblBackGround.setLayout(null);

        lblTitle.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 24)); // NOI18N
        lblTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitle.setText("HOW TO PLAY");
        lblTitle.setMaximumSize(new java.awt.Dimension(100, 50));
        lblTitle.setMinimumSize(new java.awt.Dimension(100, 50));
        lblBackGround.add(lblTitle);
        lblTitle.setBounds(250, 20, 170, 30);

        logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/MenuImg/logo.png"))); // NOI18N
        lblBackGround.add(logo);
        logo.setBounds(0, 0, 200, 67);

        lblUpAndDown.setIcon(new javax.swing.ImageIcon(getClass().getResource("/MenuImg/upandown.png"))); // NOI18N
        lblUpAndDown.setText("jLabel1");
        lblBackGround.add(lblUpAndDown);
        lblUpAndDown.setBounds(50, 110, 80, 140);

        lblPlay.setIcon(new javax.swing.ImageIcon(getClass().getResource("/MenuImg/play.png"))); // NOI18N
        lblPlay.setText("jLabel3");
        lblBackGround.add(lblPlay);
        lblPlay.setBounds(30, 70, 120, 35);

        lblTextDown.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblTextDown.setText("<html><br/>Press the \"Down Arrow\" key to make the dinosaur crouch to avoid something (a bird).<br/> </html>");
        lblBackGround.add(lblTextDown);
        lblTextDown.setBounds(170, 170, 470, 80);

        lblTextPlay1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblTextPlay1.setText("<html>     <br/>Press the \"Play\" button on the screen and the dinosaur will start running.<br/> </html>");
        lblBackGround.add(lblTextPlay1);
        lblTextPlay1.setBounds(170, 50, 470, 70);

        lblTextUp.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblTextUp.setText("<html>     <br/>Press the \"Up Arrow\" key to let the dinosaur jump over the cactus.<br/> </html>");
        lblBackGround.add(lblTextUp);
        lblTextUp.setBounds(170, 110, 470, 70);

        btnBack.setBackground(Color.decode("#f7f7f7"));
        btnBack.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 18)); // NOI18N
        btnBack.setText("Back to menu");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });
        lblBackGround.add(btnBack);
        btnBack.setBounds(510, 238, 160, 33);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/data/cloud.PNG"))); // NOI18N
        lblBackGround.add(jLabel1);
        jLabel1.setBounds(10, 50, 48, 26);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/data/cloud.PNG"))); // NOI18N
        lblBackGround.add(jLabel2);
        jLabel2.setBounds(200, 60, 48, 26);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/data/cloud.PNG"))); // NOI18N
        lblBackGround.add(jLabel3);
        jLabel3.setBounds(360, 20, 48, 26);

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/data/cloud.PNG"))); // NOI18N
        lblBackGround.add(jLabel4);
        jLabel4.setBounds(540, 60, 48, 26);

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/data/cloud.PNG"))); // NOI18N
        lblBackGround.add(jLabel5);
        jLabel5.setBounds(630, 30, 48, 26);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblBackGround, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 704, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblBackGround, javax.swing.GroupLayout.DEFAULT_SIZE, 304, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
        this.dispose();
        JFrame menu = new MainScreen();
        menu.setVisible(true);
    }//GEN-LAST:event_btnBackActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JPanel lblBackGround;
    private javax.swing.JLabel lblPlay;
    private javax.swing.JLabel lblTextDown;
    private javax.swing.JLabel lblTextPlay1;
    private javax.swing.JLabel lblTextUp;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JLabel lblUpAndDown;
    private javax.swing.JLabel logo;
    // End of variables declaration//GEN-END:variables
}
